version: '3.8'

services:
  # PostgreSQL - Base principale pour les utilisateurs
  postgres:
    image: postgres:15-alpine
    container_name: cleanarchi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cleanarchi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - cleanarchi_network

  # MongoDB - Pour les logs et données non-relationnelles
  mongodb:
    image: mongo:7.0
    container_name: cleanarchi_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: cleanarchi
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - cleanarchi_network

  # Redis - Pour les sessions et cache
  redis:
    image: redis:7.2-alpine
    container_name: cleanarchi_redis
    restart: unless-stopped
    command: redis-server --requirepass password123 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cleanarchi_network

  # pgAdmin4 - Interface d'administration PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cleanarchi_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cleanarchi.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - cleanarchi_network
    depends_on:
      - postgres

  # Mongo Express - Interface d'admin pour MongoDB
  mongo-express:
    image: mongo-express:latest
    container_name: cleanarchi_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - cleanarchi_network
    depends_on:
      - mongodb

  # Redis Commander - Interface d'admin pour Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: cleanarchi_redis_commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379:0:password123
    networks:
      - cleanarchi_network
    depends_on:
      - redis

  # Application NestJS - Clean Architecture (Development Mode)
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: cleanarchi_app_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9229:9229"  # Port pour le debug Node.js
    environment:
      NODE_ENV: development
      PORT: 3000
      
      # Database Connections
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: password123
      DB_DATABASE: cleanarchi
      
      # MongoDB Connection
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/cleanarchi?authSource=admin
      
      # Redis Connection
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password123
      
      # JWT Secrets (développement - NE PAS UTILISER EN PRODUCTION!)
      ACCESS_TOKEN_SECRET: dev-access-token-secret-32characters
      REFRESH_TOKEN_SECRET: dev-refresh-token-secret-32characters
      ACCESS_TOKEN_EXPIRATION: 3600
      REFRESH_TOKEN_EXPIRATION_DAYS: 30
      
      # Security (mode développement)
      BCRYPT_ROUNDS: 4
      
      # Application
      APP_NAME: "Clean Architecture NestJS (Development)"
      APP_VERSION: "1.0.0-dev"
      
    volumes:
      - .:/app  # Mount du code source pour hot reload
      - /app/node_modules  # Volume anonyme pour node_modules
      - ./logs:/app/logs
    networks:
      - cleanarchi_network
    depends_on:
      - postgres
      - mongodb
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 60s  # Plus long en dev
      timeout: 15s
      retries: 3
      start_period: 60s  # Plus de temps pour démarrer en dev

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  cleanarchi_network:
    driver: bridge
